### ISSUE TITLE
DataProxyPlugin has no attribute 'before_create'

### ISSUE THREAD

**Issue by beechnut** [cphsolutionslab/ckanext-dataproxy#8]
I have the `dataproxy` plugin enabled in a CKAN instance, but when I try to upload a resource (be it a DataProxy resource or otherwise), it throws an error. When I tried to upload a file, I received:

![screen shot 2015-03-11 at 2 33 21 pm](https://cloud.githubusercontent.com/assets/1887182/6604173/1b25e25e-c7fd-11e4-80b2-d213630aa9f1.png)

The stack trace looks like:

``` sh
File '/usr/lib/ckan/default/src/ckan/ckan/controllers/package.py', line 708 in new_resource
  get_action('resource_create')(context, data)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py', line 424 in wrapped
  result = _action(context, data_dict, **kw)
File '/usr/lib/ckan/default/src/ckanext-dataproxy/ckanext/dataproxy/logic/action/create.py', line 32 in dataproxy_resource_create
  return orig_resource_create(context, data_dict)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py', line 424 in wrapped
  result = _action(context, data_dict, **kw)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py', line 290 in resource_create
  plugin.before_create(context, data_dict)
AttributeError: 'DataProxyPlugin' object has no attribute 'before_create'
```

My best guess at the moment is that at [this line](https://github.com/ckan/ckan/blob/master/ckan/logic/action/create.py#L290), it needs to call the plugin's `before_create`, but the dataproxy doesn't implement it. Not sure if this is the case, however.

Thanks for any guidance you can provide.

cc @allthesignals

**Comment by beechnut** [comment]
I set up a Dataset with a CSV Resource on a dataproxy-free installation and it worked. I put dataproxy back, and tried to update the dataset with 1) a database connection and then 2) the same exact CSV. This is the error that I received.

![screen shot 2015-03-13 at 5 57 33 pm](https://cloud.githubusercontent.com/assets/1887182/6647973/8980b20c-c9aa-11e4-9d43-d04a37eaa683.png)

**Comment by beechnut** [comment]
This was due to a version conflict. @ozooner is working on a 2.3-compatible plugin.

**Comment by khanh78** [comment]
Hello,
I have the same error with trying Postgresql. .
Do you have found any solution ?

**Comment by ozooner** [comment]
Hi,

If you are using version 2.3, switch to v2.3 branch.

**Comment by khanh78** [comment]
Hi
I'm using the last version CKAN 2.5

 <meta name="generator" content="ckan 2.5.0a" />
May this version is not stable.
Do you advice to install CKAN version 2.3 ?

Thanks for your helps

**Comment by ozooner** [comment]
Yeah, currently version 2.2.1 (master) and 2.3 (v2.3) have been tested.

**Comment by khanh78** [comment]
Thanks
I'll try to install CKAN version 2.3
Is it the same 2.3 and v2.3 on your message :)

**Comment by ozooner** [comment]
By v2.3 I meant the branch name, so yes.

**Comment by khanh78** [comment]
Hi,

Could you tell me which CKAN version are you using with datapusher ?
do you install datapusher from source or package ?

**Comment by ozooner** [comment]
I am not using data pusher at all, however there is no reason why it shouldn't work with this extension.

**Comment by khanh78** [comment]
which extension do you use to preview some resource ?

**Comment by ozooner** [comment]
It depends on the resource type. This extension is about displaying database tables in CKAN as pageable/sortable tables. If you are looking to display other types of resources, please refer to CKAN documentation.

**Comment by reederz** [comment]
I'm locking the issue because the discussion here is not related to it
